library(fastgssa)
library(plyr)
library(tidyverse)
library(stringr)
library(pheatmap)
library(parallel)
library(PRISM)
qsub_conf = qsub_configuration(exec.before = c("module unload python", "module load python"), memory = "10G")
library(readr)
library(Biobase)
library(igraph)
library(dyngen)
library(cowplot)
library(magrittr)

source("scripts/2/testje4_functions.R")
source("scripts/2/ssa_deterministic.R")

library(dambiutils)
