library(fastgssa)
library(plyr)
library(tidyverse)
library(stringr)
library(pheatmap)
library(parallel)
library(PRISM)
qsub.conf = qsub.configuration(exec.before = c("module unload python", "module load python", "module load R/x86_64/3.2.2"), memory = "10G")
library(readr)
library(Biobase)
library(igraph)
library(dyngen)
library(cowplot)
library(magrittr)

source("scripts/4/testje4_functions.R")
source("scripts/4/ssa_deterministic.R")

library(dambiutils)
