library(plyr)
library(tidyverse)
library(dplyr)
library(fastgssa)
library(stringr)
library(pheatmap)
library(parallel)
library(PRISM)
qsub_conf = qsub_configuration(exec.before = c("module unload python", "module load python", "module load R/x86_64/3.2.2"), memory = "1G")
library(readr)
library(Biobase)
library(igraph)
library(dyngen)
library(cowplot)
library(magrittr)

library(dambiutils)
