// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_ssa_em
SEXP make_ssa_em(double h, double noise_strength);
RcppExport SEXP _dyngen_make_ssa_em(SEXP hSEXP, SEXP noise_strengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type noise_strength(noise_strengthSEXP);
    rcpp_result_gen = Rcpp::wrap(make_ssa_em(h, noise_strength));
    return rcpp_result_gen;
END_RCPP
}
// make_ssa_direct
SEXP make_ssa_direct();
RcppExport SEXP _dyngen_make_ssa_direct() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(make_ssa_direct());
    return rcpp_result_gen;
END_RCPP
}
// simulate
List simulate(SEXP transition_fun, SEXP ssa_alg, const NumericVector& initial_state, const NumericVector& params, const NumericMatrix& nu, const double final_time, const double max_duration, const bool stop_on_neg_state, const bool stop_on_neg_propensity, const bool verbose, const double console_interval);
RcppExport SEXP _dyngen_simulate(SEXP transition_funSEXP, SEXP ssa_algSEXP, SEXP initial_stateSEXP, SEXP paramsSEXP, SEXP nuSEXP, SEXP final_timeSEXP, SEXP max_durationSEXP, SEXP stop_on_neg_stateSEXP, SEXP stop_on_neg_propensitySEXP, SEXP verboseSEXP, SEXP console_intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type transition_fun(transition_funSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ssa_alg(ssa_algSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const double >::type final_time(final_timeSEXP);
    Rcpp::traits::input_parameter< const double >::type max_duration(max_durationSEXP);
    Rcpp::traits::input_parameter< const bool >::type stop_on_neg_state(stop_on_neg_stateSEXP);
    Rcpp::traits::input_parameter< const bool >::type stop_on_neg_propensity(stop_on_neg_propensitySEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double >::type console_interval(console_intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate(transition_fun, ssa_alg, initial_state, params, nu, final_time, max_duration, stop_on_neg_state, stop_on_neg_propensity, verbose, console_interval));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dyngen_make_ssa_em", (DL_FUNC) &_dyngen_make_ssa_em, 2},
    {"_dyngen_make_ssa_direct", (DL_FUNC) &_dyngen_make_ssa_direct, 0},
    {"_dyngen_simulate", (DL_FUNC) &_dyngen_simulate, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_dyngen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
