# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate <- function(transition_fun, ssa_alg, initial_state, params, nu, final_time, max_duration, stop_on_neg_state, stop_on_neg_propensity, verbose, console_interval) {
    .Call('_dyngen_simulate', PACKAGE = 'dyngen', transition_fun, ssa_alg, initial_state, params, nu, final_time, max_duration, stop_on_neg_state, stop_on_neg_propensity, verbose, console_interval)
}

#' @export
ssa_direct <- function() {
    .Call('_dyngen_ssa_direct', PACKAGE = 'dyngen')
}

#' @export
ssa_em <- function(h = .01, noise_strength = 2.0) {
    .Call('_dyngen_ssa_em', PACKAGE = 'dyngen', h, noise_strength)
}

